/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        black: "var(--black)",
        "blue-shadeb05": "var(--blue-shadeb05)",
        "blue-shadeb1": "var(--blue-shadeb1)",
        "blue-shadeb2": "var(--blue-shadeb2)",
        "blue-shadeb3": "var(--blue-shadeb3)",
        "blue-shadeb4": "var(--blue-shadeb4)",
        "blue-shadeb5": "var(--blue-shadeb5)",
        "blue-shadeb6": "var(--blue-shadeb6)",
        "blue-shadeb7": "var(--blue-shadeb7)",
        "-active-citizen-r": "var(---active-citizen-r)",
        "-active-citizen-r-sl": "var(---active-citizen-r-sl)",
        "-active-citizen-r2": "var(---active-citizen-r2)",
        "-b-sl": "var(---b-sl)",
        "-black-shade-bl2": "var(---black-shade-bl2)",
        "-black-shade-bl4": "var(---black-shade-bl4)",
        "-black-shade-bl5": "var(---black-shade-bl5)",
        "-black-shade-bl6": "var(---black-shade-bl6)",
        "-black-sl": "var(---black-sl)",
        "-co-creator-or": "var(---co-creator-or)",
        "-co-creator-or1": "var(---co-creator-or1)",
        "-co-creator-orbg": "var(---co-creator-orbg)",
        "-color": "var(---color)",
        "-core-sk1": "var(---core-sk1)",
        "-core-sk2": "var(---core-sk2)",
        "-core-skybg": "var(---core-skybg)",
        "-electives-brown": "var(---electives-brown)",
        "-electives-brown-sl": "var(---electives-brown-sl)",
        "-electives-brown1": "var(---electives-brown1)",
        "-gr9": "var(---gr9)",
        "-r-sl2": "var(---r-sl2)",
        "-rbg": "var(---rbg)",
        "-white-shade-w10": "var(---white-shade-w10)",
        "-white-shade-w5": "var(---white-shade-w5)",
        "-white-shade-w6": "var(---white-shade-w6)",
        "-white-shade-w7": "var(---white-shade-w7)",
        "-white-shade-w8": "var(---white-shade-w8)",
        "-white-shade-w9": "var(---white-shade-w9)",
        "-ybg": "var(---ybg)",
        "-yellow-shade-y0-5": "var(---yellow-shade-y0-5)",
        "-yellow-shade-y1": "var(---yellow-shade-y1)",
        "-yellow-shade-y10": "var(---yellow-shade-y10)",
        "-yellow-shade-y2": "var(---yellow-shade-y2)",
        "-yellow-shade-y3": "var(---yellow-shade-y3)",
        "-yellow-shade-y5": "var(---yellow-shade-y5)",
        "-yellow-shade-y5-5": "var(---yellow-shade-y5-5)",
        "-yellow-shade-y6": "var(---yellow-shade-y6)",
        "-yellow-shade-y7": "var(---yellow-shade-y7)",
        "-yellow-shade-y8": "var(---yellow-shade-y8)",
        "-yellow-shade-ybg": "var(---yellow-shade-ybg)",
        "gray-shadegr05": "var(--gray-shadegr05)",
        "gray-shadegr10": "var(--gray-shadegr10)",
        "gray-shadegr3": "var(--gray-shadegr3)",
        "gray-shadegr5": "var(--gray-shadegr5)",
        "gray-shadegr6": "var(--gray-shadegr6)",
        "gray-shadegr95": "var(--gray-shadegr95)",
        white: "var(--white)",
      },
      fontFamily: {
        h1: "var(--h1-font-family)",
        h2: "var(--h2-font-family)",
        h3: "var(--h3-font-family)",
        h4: "var(--h4-font-family)",
        h5: "var(--h5-font-family)",
        h6: "var(--h6-font-family)",
        h7: "var(--h7-font-family)",
      },
      boxShadow: {
        "box-shadow": "var(--box-shadow)",
        "sd-1": "var(--sd-1)",
      },
    },
    variants: {
      extend: {
        backdropBlur: ["responsive"],
        backdropFilter: ["responsive"],
      },
    },
  },
  plugins: [],
};
